#!/bin/bash

# - Exit if some command fails
set -o errexit
# - Exit if some command pipe fails
set -o pipefail
# - Exit if any variable is not set
set -o nounset

# - Define db URL passing the data defined in .envs/.local/.postgres
export DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"

# - Function to connect to the database
postgres_ready() {
python << END
import sys
import psycopg2
try:
   psycopg2.connect(
      dbname="${POSTGRES_DB}",
      user="${POSTGRES_USER}",
      password="${POSTGRES_PASSWORD}",
      host="${POSTGRES_HOST}",
      port="${POSTGRES_PORT}",
   )
except psycopg2.OperationalError:
   sys.exit(-1)
sys.exit(0)
END
}
until postgres_ready; do
>&2 echo "Waiting for PostgreSQL to become available.....:-("
sleep 1
done
>&2 echo "PostgreSQL is ready!!!!.....:-)"


# - Ensure the docker use the command paramater that the user passes in
exec "$@"
